#!/bin/bash
# Things you need to adjust:
#********************************************************************
# locations of executables provided by user
alignparts_lmbfgs=/home/jlr/programs/k2_lmbfgs/alignparts_lmbfgs.exe
#********************************************************************
# input/out file information
movielist=movies.txt           # name of list of movie files
coordlist=coords.txt           # name of list of coordinate files
particlepath=Particles/        # directory where particles are located (output)
moviepath=Micrographs/         # directory where movies are located (input)
lmbfgsflag=_lmbfgs             # file name modifier for locally aligned particle stacks (use \"\" to not modify root of name)
lmbfgsext=mrcs                 # extension for locally aligned particle stacks
#********************************************************************
# particle and movie information 
boxsize=256                    # boxsize for particles (in pixels)
particleradius=86              # radius for particles within box (in pixels)
pixelsize=1.45                 # pixel size (in Angstroms)
framex=3838                    # x-dimension of movies (in pixels)
framey=3710                    # y-dimension of movies (in pixels)
#********************************************************************
# frame information provided
framefirstali=1                # first frame to be used in alignment
framelastali=30                # last frame to be used in alignment
framefirstave=1                # first frame to be used in average of frames
framelastave=30                # last frame to be used in average of frames
#********************************************************************
# trajectory smoothing information provided by user
smooth=1.0d4                   # specifies the amount of smoothing forced on trajectories of particles
zeroframe=15                   # which frame is considers as unshifted (MUST MATCH THE ZEROFRAME FOR WHOLE FRAME ALIGNMENT)
exaggerate=5                   # factor by which particle trajectories should be exaggerated in vector file
invertoutput=1                 # 1 inverts output from movie densities, 0 does not
localavg=1                     # 1 performs local averaging of trajectories, 0 turns off this feature
localavgsigma=500              # the standard deviation used to weight local averaging
#********************************************************************
# Exposure weighting (optional)
expweight=1                    # 1 turns on exposure weighting, 0 turns off exposure weighting
akv=200                        # microscope accelerating voltage in kV
expperframe=1.0                # Exposure per frame in electrons per Angstrom squared
#********************************************************************
# Motion weighting (optional)
motweight=1                    # 1 turns on motion weigting, 0 turns off motion weighting
# Things you do not usually need to adjust:
#=================================================================
# Files and info generated by alignparts_starfilehandler and used by alignparts_lmbfgs
vecext=vec                     # extension for output vector files
# Alignparts_lmbfgs variables that do not usually need adjustment
maxparts=100000                # maximum number of particles that may be in a micrograph
nsigma=5                       # standard deviations above the mean to remove outlier pixels
rmax1=500                      # Low resolution cutoff (in Angstroms) used for alignment
rmax2=40                       # High resolution cutoff (in Angstroms) used for alignment
bfactor=2000                   # B-factor (in A**2) used for alignment
factr=1d7                      # Accuracy of minimizer (eg.1.0d7=1.0x10^7 in dble precision)
#=====================================================================

time $alignparts_lmbfgs << eot
$movielist
$coordlist
$boxsize,0,$particleradius,$pixelsize,$nsigma,$rmax1,$rmax2
$motweight,$expweight,$akv,$expperframe
$bfactor,$smooth,$exaggerate,$zeroframe,$invertoutput
$localavg,$maxparts,$localavgsigma
$framefirstali,$framelastali,$framefirstave,$framelastave
$factr
$moviepath
$particlepath
$lmbfgsflag
$vecext
$lmbfgsext
eot